### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2

### ISSUE THREAD

**Issue by claui** [claui/funiculi#5]
```shell
$ sudo chroot /var/lib/debbuild/x86_64/root funiculi status
Traceback (most recent call last):
  File "/usr/bin/funiculi", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/python3/dist-packages/funiculi/cli.py", line 21, in run
    fire.Fire(api.Api, command=list(args) + sys.argv[1:])
  File "/usr/lib/python3/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/lib/python3/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/lib/python3/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/lib/python3/dist-packages/funiculi/api.py", line 71, in status
    return self._send('PW?')
  File "/usr/lib/python3/dist-packages/funiculi/api.py", line 102, in _send
    process = subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 2023, in _communicate
    stderr = self._translate_newlines(stderr,
  File "/usr/lib/python3.9/subprocess.py", line 1011, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 31: ordinal not in range(128)
```

**Comment by claui** [comment]
Completed with #6.
